### ISSUE TITLE
网络层图片地址问题

### ISSUE THREAD

**Issue by LLLeoLi** [echo17666/BUAA2022-Computer-Networks#6]
- 闭环控制 ：事先不考虑有关发生拥塞的各种因素，采用image.png，及时检测哪里出现了拥塞，然后将拥塞信息传到合适的地方，以便调整网络系统的运行，并解决出现的问题。闭环控制是基于反馈环路的概念，是一种动态的方法。

**Comment by echo17666** [comment]
改了改了QAQ
